#!/usr/bin/env python3
"""Rebuild report tables from the bundled September 8, 2026 result snapshot.

Uses only the Python standard library. This does not rerun the engineering
model or update the report's written interpretation.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "source_data"
TABLES = ROOT / "tables"


def read(name):
    with (DATA / name).open(newline="") as stream:
        return list(csv.DictReader(stream))


def num(row, key):
    return float(row[key])


def fmt(value, digits=2):
    value = float(value)
    if abs(value) < 0.5 * 10 ** (-digits):
        value = 0.0
    return f"{value:.{digits}f}"


def label(shape):
    return {"uniform": "Uniform", "front_loaded": "Front-loaded",
            "back_loaded": "Back-loaded"}[shape]


def table(name, columns, headers, rows):
    content = ["% Generated by generate_tables.py from source_data/.",
               r"\begin{tabular}{" + columns + "}", r"\toprule",
               " & ".join(headers) + r" \\", r"\midrule"]
    content.extend(" & ".join(row) + r" \\" for row in rows)
    content.extend([r"\bottomrule", r"\end{tabular}", ""])
    (TABLES / name).write_text("\n".join(content))


def main():
    TABLES.mkdir(exist_ok=True)
    scenarios = read("scenarios.csv")
    selection = json.loads((DATA / "selection.json").read_text())
    selected = [r for r in scenarios if r["design_id"] == selection["selected"]["design_id"]]
    design = [r for r in selected if num(r, "rainfall_mm") == 50]
    assert len(scenarios) == 216 and len(selected) == 9 and len(design) == 3
    assert all(r["all_pass"] == "True" for r in design)
    assert all(num(r, "dt_s") == 1.875 for r in scenarios)
    assert selection["selected"]["capacity_m3"] == 150

    table("design_events.tex", "lrrrrrr",
          ["Shape", r"\shortstack{Baseline\\(L/s)}", r"\shortstack{Detained\\(L/s)}",
           r"\shortstack{Reduction\\(\%)}", r"\shortstack{Max. storage\\(m$^3$)}",
           r"\shortstack{Overflow\\(m$^3$)}", r"\shortstack{Drawdown\\(h)}"],
          [[label(r["shape"]), fmt(num(r, "baseline_peak_m3_s") * 1000),
            fmt(num(r, "peak_downstream_m3_s") * 1000), fmt(r["peak_reduction_pct"]),
            fmt(r["maximum_storage_m3"]), fmt(r["overflow_m3"], 3),
            fmt(r["drawdown_h_after_rain"])] for r in design])

    table("peak_timing.tex", "lrrr", ["Shape", "Baseline peak (min)", "Detained peak (min)", "Peak delay (min)"],
          [[label(r["shape"]), fmt(r["baseline_time_to_peak_min"]), fmt(r["time_to_peak_min"]),
            fmt(num(r, "time_to_peak_min") - num(r, "baseline_time_to_peak_min"))] for r in design])

    baselines = read("baselines.csv")
    volume_rows = []
    for depth in (25, 50, 100):
        r = next(r for r in baselines if num(r, "rainfall_mm") == depth)
        volume_rows.append([str(depth), fmt(num(r, "parking_runoff_m3") / 4, 3),
                            fmt(r["parking_runoff_m3"], 3), fmt(r["direct_rain_m3"], 3),
                            fmt(r["total_inflow_m3"], 3)])
    table("event_volumes.tex", "rrrrr", [r"\shortstack{Rainfall\\(mm)}", r"\shortstack{Parking excess\\(mm)}",
          r"\shortstack{Parking runoff\\(m$^3$)}", r"\shortstack{Direct rain\\(m$^3$)}",
          r"\shortstack{Total input\\(m$^3$)}"], volume_rows)

    table("all_events.tex", "rlrrrrr",
          [r"\shortstack{Rain\\(mm)}", "Shape", r"\shortstack{Baseline\\(L/s)}",
           r"\shortstack{Detained\\(L/s)}", r"\shortstack{Reduction\\(\%)}",
           r"\shortstack{Overflow\\(m$^3$)}", r"\shortstack{Drawdown\\(h)}"],
          [[fmt(r["rainfall_mm"], 0), label(r["shape"]), fmt(num(r, "baseline_peak_m3_s") * 1000),
            fmt(num(r, "peak_downstream_m3_s") * 1000), fmt(r["peak_reduction_pct"]),
            fmt(r["overflow_m3"], 3), fmt(r["drawdown_h_after_rain"])] for r in selected])

    table("water_budget.tex", "lrrrr", ["50 mm shape", r"Input (m$^3$)",
          r"Discharged (m$^3$)", r"Overflow (m$^3$)", r"Residual (m$^3$)"],
          [[label(r["shape"]), fmt(r["total_inflow_m3"], 6), fmt(r["controlled_discharge_m3"], 6),
            fmt(r["overflow_m3"], 6), fmt(r["residual_storage_m3"], 6)] for r in design])

    convergence = read("convergence.csv")
    conv_rows = []
    for coarse, fine in ((30, 15), (15, 7.5), (7.5, 3.75), (3.75, 1.875)):
        group = [r for r in convergence if num(r, "coarse_dt_s") == coarse]
        assert len(group) == 216
        maxima = [max(num(r, key) for r in group) for key in
                  ("peak_downstream_m3_s_relative_change", "maximum_storage_m3_relative_change",
                   "overflow_change_m3", "drawdown_change_s")]
        conv_rows.append([f"{coarse:g} / {fine:g}", fmt(maxima[0] * 100, 4), fmt(maxima[1] * 100, 4),
                          fmt(maxima[2], 6), fmt(maxima[3], 3)])
    table("convergence.tex", "rrrrr", ["Steps (s)", r"\shortstack{Peak change\\(\%)}",
          r"\shortstack{Storage change\\(\%)}", r"\shortstack{Overflow change\\(m$^3$)}",
          r"\shortstack{Drawdown change\\(s)}"], conv_rows)

    sensitivity = read("sensitivity.csv")
    assert len(sensitivity) == 27
    sens_rows = []
    for parameter, text in (("curve_number", "Curve number"), ("lag_min", "Lag (min)"),
                             ("discharge_coefficient", r"$C_d$")):
        for value in sorted({num(r, "parameter_value") for r in sensitivity if r["varied_parameter"] == parameter}):
            group = [r for r in sensitivity if r["varied_parameter"] == parameter and num(r, "parameter_value") == value]
            sens_rows.append([text, f"{value:g}", fmt(min(num(r, "peak_reduction_pct") for r in group)),
                              fmt(max(num(r, "overflow_m3") for r in group), 3),
                              fmt(max(num(r, "drawdown_h_after_rain") for r in group)),
                              "Pass" if all(r["all_pass"] == "True" for r in group) else r"\textbf{Fail}"])
    table("sensitivity.tex", "lrrrrl", ["Parameter", "Value", r"\shortstack{Min. reduction\\(\%)}",
          r"\shortstack{Max. overflow\\(m$^3$)}", r"\shortstack{Max. drawdown\\(h)}", "All shapes"], sens_rows)

    designs = read("design_selection.csv")
    assert len(designs) == 24 and sum(r["all_design_storms_pass"] == "True" for r in designs) == 4
    table("all_designs.tex", "rrrrrrl", [r"\shortstack{Capacity\\(m$^3$)}", r"\shortstack{Depth\\(m)}",
          r"\shortstack{Opening\\(mm)}", r"\shortstack{Min. reduction\\(\%)}",
          r"\shortstack{Max. overflow\\(m$^3$)}", r"\shortstack{Max. drawdown\\(h)}", "Result"],
          [[fmt(r["capacity_m3"], 0), fmt(r["storage_depth_m"]), fmt(r["outlet_side_mm"], 0),
            fmt(r["worst_peak_reduction_pct"]), fmt(r["worst_overflow_m3"], 3), fmt(r["worst_drawdown_h"]),
            (r"\textbf{Selected}" if r["design_id"] == selection["selected"]["design_id"] else
             "Pass" if r["all_design_storms_pass"] == "True" else "Fail")] for r in designs])
    print(f"Generated {len(list(TABLES.glob('*.tex')))} tables from the bundled result snapshot.")


if __name__ == "__main__":
    main()
